Module7 task3
htmlacademy-react/1261203-six-cities-8 pull request #10
Opened 2021-12-08 17:17 UTC by romkolisnyk

2021-12-10 09:50 UTC, Shramkoweb requested changes

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/components/app/app.tsx
> +        <Route path={AppRoute.NotFound}>
А разве 404 и NotFound это не одно и то же?

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/components/review-form/review-form.tsx
> +  const dispatch = useDispatch();
Блин так странно выглядит каждый раз доставать `dispatch` =(

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/components/review-form/review-form.tsx
> +    dispatch(postCommentAction(review, Number(id)));
```suggestion
    dispatch(postCommentAction(review, parseInt(id)));
```
Почитай думаю так будет код немного стабильнее ? https://thisthat.dev/number-constructor-vs-parse-int/

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/components/review-form/review-form.tsx
> +    // TODO: Add debounce
👍

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/components/review-form/review-form.tsx
> +    setIsCompletedReview(review.comment.length >= 50);
Там вроде >50 символов и хотя бы выбрана одна из звездочек

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/components/review-form/review-form.tsx
>      <form className="reviews__form form" onSubmit={handleSubmit}>
Возможно стоит рейтинг и коммент делать отдельно. Мне кажеться у тебя будет лишний рендер тут если что-то из этого меняеться. Например когда меняется рейтинг то будет и комент ререндерится?

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/const.ts
> +export const RATINGS = {
Это не массив, а перечесление. Почитай требования к именованияю

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/hooks/useScrollTop.tsx
> +export default function ScrollToTop(): null {
хуки именуються как use чего то там. https://ru.reactjs.org/docs/hooks-custom.html

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +      await api.post(`/comments/${id}`, comment).then(() => dispatch(fetchCurrentOfferCommentsAction(id)));
А что тут забыл then ?)

2021-12-10 09:50 UTC, Shramkoweb commented on project/src/types/comment.ts
> +export type Comment = {
Чет не смог нагуглить как сделать тип на основе одного и не копипастить все. =( Есть варианрт с опциональным полем, но выглядит как костыль

2021-12-12 20:57 UTC, romkolisnyk commented on project/src/components/review-form/review-form.tsx
>      <form className="reviews__form form" onSubmit={handleSubmit}>
Сделаю когда пройду урок по оптимизации, чтобы сразу сделать все правильно и с пониманием проблемы)

2021-12-13 12:42 UTC, Shramkoweb commented
LGTM

2021-12-13 12:42 UTC, merged