Module7 task1
htmlacademy-react/1261203-six-cities-8 pull request #8
Opened 2021-11-05 14:40 UTC by romkolisnyk

2021-11-07 09:51 UTC, Shramkoweb requested changes

2021-11-07 09:51 UTC, Shramkoweb commented on project/src/api/api.ts
> +const BACKEND_URL = 'https://8.react.pages.academy/six-cities';
А если это будет не бекенд, а другой сервис или другой фронт? `BASE_URL` или `BASE`

https://developer.mozilla.org/ru/docs/Web/API/URL/URL#%D0%BF%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D1%8B вот в доке такой параметр называют просто base

2021-11-07 09:51 UTC, Shramkoweb commented on project/src/components/locations/locations.tsx
> +import { CityName } from '../../const';
👍

2021-11-07 09:51 UTC, Shramkoweb commented on project/src/components/main-page/main-page.tsx
> +              store.getState().offers.length === 0
Если тебе что-то надо из стора то дотань это в mapStateToProps. store.getState() это нативная возможность редакса, у нас же есть react-redux который всю эту подгатоную делает сам.

2021-11-07 09:51 UTC, Shramkoweb commented on project/src/components/main-page/main-page.tsx
> +                city={store.getState().city}
mapStateToProps

2021-11-07 09:51 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +    const { data } = await api.get(APIRoute.GetOffers);
```suggestion
    const { data } = await api.get(APIRoute.GetOffers, {transformResponse : [(data) => data.map((offer: OfferFromServer) => Adapter.offerToClient(offer))]});
```
 должно работать не? https://github.com/axios/axios#request-config

2021-11-07 09:51 UTC, Shramkoweb commented on project/src/store/reducer.ts
> +  },
Плохая затея - хоть и удобно. В будущем с такой структурой сложно будет рабоать если надо ее трансформировать или что-то доставать. Нужно будет следаить за вложеностью и т/д.

2021-11-07 09:51 UTC, Shramkoweb commented on project/src/store/reducer.ts
> +  },
https://redux.js.org/tutorials/fundamentals/part-7-standard-patterns#normalized-state

2021-11-07 13:43 UTC, romkolisnyk commented on project/src/api/api.ts
> +const BACKEND_URL = 'https://8.react.pages.academy/six-cities';
Взял название с примера проета Академии. Но с тобой согласен, переименую.

2021-11-08 21:05 UTC, romkolisnyk commented on project/src/store/api-actions.ts
> +    const { data } = await api.get(APIRoute.GetOffers);
Не работаить
![image](https://user-images.githubusercontent.com/26679133/140817946-0ac8f951-22ac-4872-bc04-5d8311552cdd.png)

2021-11-09 14:28 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +    const { data } = await api.get(APIRoute.GetOffers);
Оки, я чекну надо глянуть что там приходит, и почему не работает.

2021-11-12 07:56 UTC, Shramkoweb approved these changes

2021-11-12 07:56 UTC, Shramkoweb commented on project/src/components/locations/locations.tsx
> +        {Object.keys(CityName).map((city) => (
Мы же это получаем на основе городов с бека? Или хардкод?

2021-11-12 07:56 UTC, Shramkoweb commented on project/src/components/map/map.tsx
> +  const [{ city }] = offers;
Шо? Шо тут происходит? Первый город? А почему первый?

2021-11-12 07:56 UTC, Shramkoweb commented on project/src/utils/filterOffersByCity.ts
> +export const filterOffersByCity = (offers: Offer[], cityName: CityName): Offer[] => offers.filter((offer) => offer.city.name === cityName);
👍

2021-11-12 07:56 UTC, merged

2021-11-12 08:00 UTC, romkolisnyk commented on project/src/components/map/map.tsx
> +  const [{ city }] = offers;
Потому что гладиолус.
А вообще, сюда приходит уже отфильтрованый по городу массив, и разве нельзя просто так взять и достать с первого элемента локацию этого города?)

2021-11-12 08:10 UTC, romkolisnyk commented on project/src/components/locations/locations.tsx
> +        {Object.keys(CityName).map((city) => (
Я это взял с перечисления городов (`enum`), который в техзадании фиксированный, т.е. у нас четко задано какие города есть, ни больше, ни меньше, и принято было решение брать это оттуда. Можно было отфильтровать и взять список городов с прилетающего с бэка массива, но мне показалось, что это лишняя логика и нагрузка на аппку, есть же красивое и простое перечисление.
А еще вдруг с бэка прилетит не Brussels, а Vsrussels, и этот город автоматически добавится в таблист, а нам такой город не нужен) Но нужно, конеч, и в моем случае логику отлавливания опечаток делать...но это уже совсем другая история. Главное, что это не попадет в таблист.

2021-11-12 08:10 UTC, romkolisnyk commented on project/src/store/api-actions.ts
> +    const { data } = await api.get(APIRoute.GetOffers);
Ти набрехав, нічого ти не зробив!

2021-11-12 08:13 UTC, Shramkoweb commented on project/src/components/locations/locations.tsx
> +        {Object.keys(CityName).map((city) => (
Да. Логика есть в этом, но ты по дефолту веришь беку так как он оперирует данными. И если на клиенте делать что-то сове появиться 2 источника правды. Какому верить?
Завтра бек тебе нагенерит еще 2 новых города - а у тебя их просто не будет =( Или наоборот прилетит 1 город, а у тебя 2 табов. Эти данны должны быть из данных с бека

2021-11-12 08:15 UTC, Shramkoweb commented on project/src/components/map/map.tsx
> +  const [{ city }] = offers;
Если он первый то бери по индексу. Или если хочешь деструкторизацию то что-то типа   const [firstSity] = offers;
а потом firstSity.city - да букв больше, но понятно что ты тут именно хотел взять первый. А сейчас это надо самому додумать ))

2021-11-12 08:24 UTC, romkolisnyk commented on project/src/components/locations/locations.tsx
> +        {Object.keys(CityName).map((city) => (
Да, я это понимаю, ты прав, но я доверился полностью ТЗ и поверил "заказчику", что ему этих городов хватает)
В общем, я тогда перепишу это под фильтр городов с бэка.
Это что, мне перечисление городов и не понадобится тогда?(