feat: Create login for login / logout
htmlacademy-react/1261203-six-cities-8 pull request #9
Opened 2021-11-15 22:30 UTC by romkolisnyk

2021-11-18 15:37 UTC, Shramkoweb requested changes

2021-11-18 15:37 UTC, Shramkoweb commented on project/package.json
> +    "react-toastify": "^8.1.0",
👍

2021-11-18 15:37 UTC, Shramkoweb commented on project/src/api/api.ts
> +      return Promise.reject(error);
Как логика этого `interceptor` работает понял?

2021-11-18 15:37 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +      toast.info('Please, log in :)');
Там не факт, что юзер не авторизован и будет 401 ошибка. Может упасть бекенд. Я бы брал ошибку в catch и ее передевал в тоаст) Или написал бы какой то провайдер который при 401 пишет человечески, что авторизуйся. А при 500 пишет, что что-то с нашим беком и так далее)

2021-11-18 15:37 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +    dispatch(redirectToRoute(AppRoute.Root));
А если бек не ответит токеном?

2021-11-18 15:37 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +    await api.delete(APIRoute.Logout);
А почему логаут вызвает метод delete ?? Как то семантика хромает

2021-11-18 15:37 UTC, Shramkoweb commented on project/src/services/token.ts
> +export const removeToken = (): void => {
getToken, saveToken, removeToken должны получать по хорошему имя ключа с кторыом они будут работать в localStorage. Сейчас же они у тебя захардкожены на один ключ((

2021-11-18 15:37 UTC, Shramkoweb commented on project/src/store/api-actions.ts
> +    removeToken();
Вот тут тоже, removeToken выглядит не очень без параметра. Я не вижу какой ключ, что где когда))

2021-11-18 15:37 UTC, Shramkoweb commented on project/src/types/user.ts
> +  'avatar_url': string,
Потерялся адаптер?))

2021-11-28 08:22 UTC, romkolisnyk commented on project/src/store/api-actions.ts
> +    removeToken();
Выбросил сервис токена вообще, т.к. если сделать просто сервис локалСтореджа, то получается, что проще написать прямое обращение к стореджу, чем усложнять структуру лишними классами/функциями.

2021-11-28 08:34 UTC, Shramkoweb approved these changes

2021-11-28 08:34 UTC, merged